[[redirects]]
  from = "/pact_broker/terraform-provider"
  to = "/pact_broker/terraform_provider"
  status = 301

[[redirects]]
  from = "/pact_broker/advanced_topics/webhooks/template_lib"
  to = "/pact_broker/webhooks/template_library"
  status = 301

[[redirects]]
  from = "/pact_broker/advanced_topics/webhooks"
  to = "/pact_broker/webhooks"
  status = 301

[[redirects]]
  from = "/consumer_version_selectors"
  to = "/pact_broker/advanced_topics/consumer_version_selectors"
  status = 301

[[redirects]]
  from = "/pending"
  to = "/pact_broker/advanced_topics/pending_pacts"
  status = 301

# Used in pact verification output
[[redirects]]
  from = "/wip"
  to = "/pact_broker/advanced_topics/wip_pacts"
  status = 301

[[redirects]]
  from = "/can_i_deploy"
  to = "/pact_broker/can_i_deploy"
  status = 301

[[redirects]]
  from = "/pact_broker/pact_broker_client_cli"
  to = "/pact_broker/client_cli"
  status = 301

[[redirects]]
  from = "/guides"
  to = "/consumer"
  status = 302

[[redirects]]
  from = "/workshops"
  to = "/implementation_guides/workshops"
  status = 302

[[redirects]]
  from = "/implementation_guides"
  to = "/implementation_guides/cli"
  status = 302

[[redirects]]
  from = "/pact_broker/advanced_topics/provider_verification_results"
  to = "/pact_broker/provider_verification_results"
  status = 301

[[redirects]]
  from = "/getting_started"
  to = "/"
  status = 302

[[redirects]]
  from = "/resources/how_to_ask_for_help"
  to = "/help/how_to_ask_for_help"
  status = 301

[[redirects]]
  from = "/best_practices/consumer"
  to = "/consumer"
  status = 301

[[redirects]]
  from = "/best_practices/pact_nirvana"
  to = "/pact_nirvana"
  status = 302

[[redirects]]
  from = "/versioning"
  to = "/getting_started/versioning_in_the_pact_broker"
  status = 301

[[redirects]]
  from = "/webhooks"
  to = "/pact_broker/webhooks/"
  status = 301

[[redirects]]
  from = "/webhook_events"
  to = "/pact_broker/webhooks/#events"
  status = 301

[[redirects]]
  from = "/implementation_guides/jvm/provider_menu"
  to = "/implementation_guides/jvm/provider/junit5spring"
  status = 301

# Links below are used in the output of Pact APIs that get shown in the terminal

# Used in publish contracts response
[[redirects]]
  from = "/go/provider_verification"
  to = "/getting_started/provider_verification?utm_source=pact&utm_medium=client_library"
  status = 301
  # Used in publish contracts response

# Used in publish contracts response
[[redirects]]
  from = "/go/versioning"
  to = "/getting_started/versioning_in_the_pact_broker?utm_source=pact&utm_medium=client_library"
  status = 301

# Used in publish contracts response
[[redirects]]
  from = "/go/webhooks"
  to = "/pact_broker/webhooks/?utm_source=pact&utm_medium=client_library"
  status = 301

# Used in pact verification output
[[redirects]]
  from = "/go/pending"
  to = "/pact_broker/advanced_topics/pending_pacts?utm_source=pact&utm_medium=client_library"
  status = 301

# Used in pact verification output
[[redirects]]
  from = "/go/wip"
  to = "/pact_broker/advanced_topics/wip_pacts?utm_source=pact&utm_medium=client_library"
  status = 301

# Used in record-release help output

[[redirects]]
  from = "/go/record-deployment"
  to = "/pact_broker/recording_deployments_and_releases?utm_source=pact&utm_medium=client_library"
  status = 301

[[redirects]]
  from = "/go/record-undeployment"
  to = "/pact_broker/recording_deployments_and_releases?utm_source=pact&utm_medium=client_library"
  status = 301

[[redirects]]
  from = "/go/record-release"
  to = "/pact_broker/recording_deployments_and_releases?utm_source=pact&utm_medium=client_library"
  status = 301

[[redirects]]
  from = "/go/record-support-ended"
  to = "/pact_broker/recording_deployments_and_releases?utm_source=pact&utm_medium=client_library"
  status = 301
