name: Sync Pact docs

on:
  repository_dispatch:
    types: [pact-js-docs-updated, pact-jvm-docs-updated]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: gem install bundler -v 2.0.2
    - run: bundle install

    - run: bundle exec ruby scripts/sync/pact_js.rb
      if: github.event.action == 'pact-js-docs-updated'

    - run: bundle exec ruby scripts/sync/pact_jvm.rb
      if: github.event.action == 'pact-jvm-docs-updated'

    - uses: EndBug/add-and-commit@v4
      with:
        add: 'docs/implementation_guides'
        author_name: Github Action
        author_email: beth@bethesque.com
        message: 'chore: updated docs from trigger ${{ github.event.action }}"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
